### ISSUE TITLE
Fresh install/init is broken?

### ISSUE THREAD

**Issue by CaptainPowerTurtle** [rharkor/next-boilerplate#866]
**Describe the bug**
As far as i can see, the project can't bil installed/initlized on newer versions, the last version i got to work was 3.7.1

It will randomly throw some errors when using npm install:
`npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\Jacob\\Desktop\\next-boilerplate-3.12.0\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Jacob\Desktop\next-boilerplate-3.12.0\node_modules\@react-stately\flags\node_modules\@swc\helpers\_'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\Jacob\\Desktop\\next-boilerplate-3.12.0\\node_modules\\@react-stately\\flags\\node_modules\\@swc\\helpers\\_'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\Jacob\\Desktop\\next-boilerplate-3.12.0\\node_modules\\next',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Jacob\Desktop\next-boilerplate-3.12.0\node_modules\next\dist\esm\shared'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\Jacob\\Desktop\\next-boilerplate-3.12.0\\node_modules\\next\\dist\\esm\\shared'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
`
and will throw this one too:

`npm error path C:\Users\Jacob\Desktop\next-boilerplate-3.12.0\apps\app
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c prisma generate
npm error Prisma schema loaded from prisma\schema.prisma
npm error Error: EBUSY: resource busy or locked, unlink 'C:\Users\Jacob\Desktop\next-boilerplate-3.12.0\node_modules\prisma\query_engine-windows.dll.node'
`

running npm install again works fine, wit no errors.

After that i then run the npm run init

it then gives me this error:

`node:internal/modules/cjs/loader:464
      const err = new Error(
                  ^

Error: Cannot find module 'C:\Users\Jacob\Desktop\next-boilerplate-3.12.0\node_modules\@next-boilerplate\lib\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:464:19)
    at Module._findPath (node:internal/modules/cjs/loader:747:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1188:27)
    at a._resolveFilename (C:\Users\Jacob\Desktop\next-boilerplate-3.12.0\node_modules\tsx\dist\cjs\index.cjs:1:1729)
    at Module._load (node:internal/modules/cjs/loader:1027:27)
    at Module.require (node:internal/modules/cjs/loader:1290:19)
    at require (node:internal/modules/helpers:188:18)
    at chalk (C:\Users\Jacob\Desktop\next-boilerplate-3.12.0\packages\scripts\env-setup.ts:10:24)
    at Object.<anonymous> (C:\Users\Jacob\Desktop\next-boilerplate-3.12.0\packages\scripts\env-setup.ts:14:25)
    at Module._compile (node:internal/modules/cjs/loader:1455:14) {
  code: 'MODULE_NOT_FOUND',
  path: '\\\\?\\C:\\Users\\Jacob\\Desktop\\next-boilerplate-3.12.0\\node_modules\\@next-boilerplate\\lib\\package.json',
  requestPath: '@next-boilerplate/lib'
`

I can fix this error by going into the lib folder and do: npm run build (i don't think i should be doing that)

I then type yes, no and then gives it a name.

I can see that it then throws a lot of errors in the console, for example this one:
`ERROR  Error reading file ..\..\node_modules\@typescript-eslint\experimental-utils\node_modules\@typescript-eslint\typescript-estree\dist\parseSettings\resolveProjectList.js`

and then it is stuck/standing at: Reinstalling dependencies..., that after a while errors out.

**To Reproduce**
Fresh clone of latest version of the repository/project (I guess with a clean cache maybe?)
Run npm install
Run npm run init (throws errors)
Run npm run build in packages/lib
Run npm run init again
Type yes, no and give it a random name

**Expected behavior**
To start the project from fresh.

**Desktop (please complete the following information):**
Windows 11.
All commands have ben run with Git Bash running as admin

**Comment by rharkor** [comment]
Hi, thanks for your well described issue, I'll look into it tomorrow morning 😉

**Comment by CaptainPowerTurtle** [comment]
Sounds good.
Will look forward to try out this interesting project! 😄

**Comment by rharkor** [comment]
Hey @CaptainPowerTurtle , v3.12.2 is here
I rework and fix the init cli :open_hands: 

Tell me if it work great for you

**Comment by CaptainPowerTurtle** [comment]
@rharkor I just tried the new release, but i think the problem have been partial solved😢 

Running npm install worked in first try (yay!)

Running npm run init threw the error that it could not find the next-boilerplate\lib
Then ran the npm run build in packages\lib to fix it

I then tried to build the lib project, and ran npm run init again, and was able to go throug the 3 steps/questions, but is now stuck in a infinite loop with "Error reading file ..\..\node_modules\..."

But if i stop the loop, and then runs npm run dev, it starts fine, and i can see the sites 😄

**Comment by rharkor** [comment]
@CaptainPowerTurtle nice it seems that we are making progress ! 

## Lib not build
For this part it is quite strange because if you check the root package.json you will see that before running the `init` script I run:
`turbo run build --filter='@next-boilerplate/*'^...`
This command should detect that the `packages/lib` need to be builded. Maybe turbo doesnt act the same with windows because I have tried on linux (ubuntu) and everything works great.

## Error reading file ....\node_modules...
Can you send me the according logs please so I can determine in which step and why it is throwing this


# Temporary workaround
I heavily recommend the usage of the `devcontainer` for this project and I'm sure you will fall in love with it. If you try to work in the devcontainer you will have a great linux environment with tons of great features.
Give it :+1: 

Again thanks for your feedbacks

**Comment by CaptainPowerTurtle** [comment]
@rharkor i just tried it in devcontainers, and it works like a charm! had totally forgot that i could do that, so thank you for that suggestion!

It did however throw an exception:

` 
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}`

But as far as i can see, it did complete the setup, and the project start up just fine!

Regarding the logs, i can't seem to find them, so i sadly can't provide them 😞

**Comment by rharkor** [comment]
@CaptainPowerTurtle Okay thank you, I will be attentive to unknown errors in the future.
